language: java
jdk:
      - oraclejdk8
after_success: 
      - bash <(curl -s https://codecov.io/bash)
services: 
      - mongodb
script:
   # the following command line builds the project, runs the tests with coverage and then execute the SonarQube analysis
      - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
